# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/refs/heads/master/schema/config.json

gui:
    mouseEvents: false
    showBottomLine: false
    showCommandLog: true
    showFileTree: false
    showIcons: false
    showRandomTip: false
